meta:
  github_private_key: ((github-ssh-key.private_key))
  github_access_token: ((github-access-token))
  git_uri: git@github.com:bodymindarts/cepler.git
  git_branch: ci

  docker_registry: eu.gcr.io/misthos-network-control-plane
  docker_registry_user: ((docker-creds.username))
  docker_registry_password: ((docker-creds.password))
